package models

import (
	"time"

	"github.com/yyle88/gormcnm"
	"gorm.io/gorm"
)

// This file will be auto-generated by gormcngen
// Do not edit manually

func (p *Author) Columns() *AuthorColumns {
	return p.TableColumns(gormcnm.NewPlainDecoration())
}

type AuthorColumns struct {
	// Embedding operation functions make it easy to use // 继承操作函数便于使用
	gormcnm.ColumnOperationClass
	// The column names and types of the model's columns // 模型各列的列名和类型
	ID        gormcnm.ColumnName[uint]
	CreatedAt gormcnm.ColumnName[time.Time]
	UpdatedAt gormcnm.ColumnName[time.Time]
	DeletedAt gormcnm.ColumnName[gorm.DeletedAt]
	Name      gormcnm.ColumnName[string]
	Email     gormcnm.ColumnName[string]
	Bio       gormcnm.ColumnName[string]
	Country   gormcnm.ColumnName[string]
}

func (p *Book) Columns() *BookColumns {
	return p.TableColumns(gormcnm.NewPlainDecoration())
}

type BookColumns struct {
	// Embedding operation functions make it easy to use // 继承操作函数便于使用
	gormcnm.ColumnOperationClass
	// The column names and types of the model's columns // 模型各列的列名和类型
	ID          gormcnm.ColumnName[uint]
	CreatedAt   gormcnm.ColumnName[time.Time]
	UpdatedAt   gormcnm.ColumnName[time.Time]
	DeletedAt   gormcnm.ColumnName[gorm.DeletedAt]
	Title       gormcnm.ColumnName[string]
	ISBN        gormcnm.ColumnName[string]
	Price       gormcnm.ColumnName[float64]
	PublishedAt gormcnm.ColumnName[string]
	Status      gormcnm.ColumnName[string]
	AuthorID    gormcnm.ColumnName[uint]
}

func (p *Author) TableColumns(decoration gormcnm.ColumnNameDecoration) *AuthorColumns {
	return &AuthorColumns{
		ID:        gormcnm.Cmn(p.ID, "id", decoration),
		CreatedAt: gormcnm.Cmn(p.CreatedAt, "created_at", decoration),
		UpdatedAt: gormcnm.Cmn(p.UpdatedAt, "updated_at", decoration),
		DeletedAt: gormcnm.Cmn(p.DeletedAt, "deleted_at", decoration),
		Name:      gormcnm.Cmn(p.Name, "name", decoration),
		Email:     gormcnm.Cmn(p.Email, "email", decoration),
		Bio:       gormcnm.Cmn(p.Bio, "bio", decoration),
		Country:   gormcnm.Cmn(p.Country, "country", decoration),
	}
}

func (p *Book) TableColumns(decoration gormcnm.ColumnNameDecoration) *BookColumns {
	return &BookColumns{
		ID:          gormcnm.Cmn(p.ID, "id", decoration),
		CreatedAt:   gormcnm.Cmn(p.CreatedAt, "created_at", decoration),
		UpdatedAt:   gormcnm.Cmn(p.UpdatedAt, "updated_at", decoration),
		DeletedAt:   gormcnm.Cmn(p.DeletedAt, "deleted_at", decoration),
		Title:       gormcnm.Cmn(p.Title, "title", decoration),
		ISBN:        gormcnm.Cmn(p.ISBN, "isbn", decoration),
		Price:       gormcnm.Cmn(p.Price, "price", decoration),
		PublishedAt: gormcnm.Cmn(p.PublishedAt, "published_at", decoration),
		Status:      gormcnm.Cmn(p.Status, "status", decoration),
		AuthorID:    gormcnm.Cmn(p.AuthorID, "author_id", decoration),
	}
}
